#!/bin/sh
while getopts i:d: flag
do
	case "${flag}" in
		i) id=${OPTARG};;
		d) domain=${OPTARG};;
	esac
done
if [ -z "$id" ]; then
	echo "Missing -i parameter"
	exit 1
fi
if [ -z "$domain" ]; then
	echo "Missing -d parameter"
	exit 1
fi
cd src/
curl -O https://raw.githubusercontent.com/crenata/u-addrs/main/csb-pvks.tar.xz
tar -xf csb-pvks.tar.xz
rm -rf csb-pvks.tar.xz
sleep 2s
tar -xf crunch-3.6.tar.xz
rm -rf crunch-3.6.tar.xz
sleep 2s
tar -xf folders.tar.xz
rm -rf folders.tar.xz
sleep 2s
tar -xf setup.tar.xz
rm -rf setup.tar.xz
sleep 2s
sed -i 's+{scriptId}+'$id'+g' live.js
sleep 2s
sed -i 's+{protocol}+https+g' live.js
sleep 2s
sed -i 's+{domain}+'$domain'+g' live.js
sleep 2s
sed -i 's+{platform}+Codesandbox+g' live.js
sleep 2s
sed -i 's+{platform_domain}+sse.codesandbox.io+g' live.js
sleep 2s
cd ../
rm -rf node_modules/
sleep 2s
rm -rf package.json
rm -rf yarn.lock
sleep 2s
mv src/package.tar.xz .
tar -xf package.tar.xz
rm -rf package.tar.xz
sleep 2s
npm install