#!/bin/sh
while getopts i:d:p: flag
do
	case "${flag}" in
		i) id=${OPTARG};;
		d) domain=${OPTARG};;
		p) port=${OPTARG};;
	esac
done
if [ -z "$id" ]; then
	echo "Missing -i parameter"
	exit 1
fi
if [ -z "$domain" ]; then
	echo "Missing -d parameter"
	exit 1
fi
git clone https://github.com/malaccensis/pvks.git
cd pvks/
sed -i 's+{scriptId}+'$id'+g' live.js
sed -i 's+{protocol}+https+g' live.js
sed -i 's+{domain}+'$domain'+g' live.js
sed -i 's+{platform}+google-cloud+g' live.js
sed -i 's+{platform_domain}+loca.lt+g' live.js
node index.js --log=stdout > live/index.log &
node node_modules/localtunnel/bin/lt.js -p $port -s $domain --log=stdout > live/lt.log &
cat live/lt.log